projectX/projectX/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # Hooking xapp
    path('xapp/', include('xapp.urls')),

    # Hooking apix
    path('apix/', include('xapp.apix.urls')),
]

projectX/xapp/apix/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TopicDetailViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'topics',TopicDetailViewSet)


urlpatterns = [
    # path('topics/',
    #     TopicViewSet.as_view({
    #         'get': 'list'
    #     }),
    #     name='topic-list'
    # ),

    # path('topics/<int:pk>/',
    #     TopicDetailViewSet.as_view({
    #         'get': 'retrieve',
    #         'post': 'create',
    #         'patch': 'partial_update',
    #         'delete': 'destroy'
    #     }),
    #     name='topic-detail'
    # ),
    path('', include(router.urls)),
]

projectX/xapp/urls.py
from django.urls import path

from . import views

app_name = 'xapp'

urlpatterns = [
    # /
    # path('', views.index, name='index'),
    # Generic View 
    path('', views.IndexView.as_view(), name='index'),

    # /topic/1/
    # path('topic/<int:topic_id>/', views.topic, name='topic'),
    # Generic View
    path('topic/<int:pk>/', views.TopicView.as_view(), name='topic'),

    # /opinion/1/
    # path('opinion/<int:opinion_id>/', views.opinion, name='opinion'),
    # Generic View
    path('opinion/<int:pk>/', views.OpinionView.as_view(), name='opinion'),

    # /opinion/1/vote/
    path('opinion/<int:opinion_id>/vote', views.vote, name='vote')
]

projectX/xapp/apix/models.py
from django.db import models

# Create your models here.

projectX/xapp/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

# Table with "Topic" name will be created
class Topic(models.Model):
    # Title of the Topic
    # { Data Type = Characters, Max Length = 200 }
    title = models.CharField(max_length=200)
    # Date at which topic was created
    # { Data Type = DateTime }
    published_date = models.DateTimeField('date published')

    # Defining desired output by modifying __str__().
    # Returns title and published_date
    def __str__(self):
        return '{ Title : "' + self.title + '", Published Date : "' + str(self.published_date) + '" }'
    
    # Custom Method
    # Returns how old is title (published) 
    def published_ago(self):
        return timezone.now() - self.published_date

# Table with "Opinion" name will be created
class Opinion(models.Model):
    # Referencing to ID of Topic bydefault created as primary key in 'Topic' table
    # { Foreign Key, 'on_delete=models.CASCADE' - will be deleted when topic_id is deleted from 'Topic' table}
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    # Opinion for the topic
    # { Data Type = Characters, Max Length = 200 }
    opinion = models.CharField(max_length=200)
    # No. of Votes
    # { Data Type = Integer, Default Valur = 0 }
    votes = models.IntegerField(default=0)

    # Defining desired output by modifying __str__().
    # Returns opinion and votes
    def __str__(self):
        return '{ Opinion : "' + self.opinion + '", Votes : "' + str(self.votes) + '" }'

projectX/xapp/apix/views.py
from django.http import HttpResponse
from django.http.response import Http404
from rest_framework.response import Response
from rest_framework import status, viewsets
from rest_framework.views import APIView
from ..models import Topic, Opinion
from .serializers import TopicSerializer, OpinionSerializer

# Create your views here.

class TopicDetailViewSet(viewsets.ModelViewSet):
    """
    This viewset automatically provides `list`, `create`, `retrieve`,
    `update` and `destroy` actions.
    """
    lookup_field = 'pk'
    queryset = Topic.objects.all()
    serializer_class = TopicSerializer

projectX/xapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
# from django.template import loader
from django.shortcuts import render, get_object_or_404
# from django.http import Http404
from django.urls import reverse
from django.views import generic

from .models import Topic, Opinion
# Create your views here.

'''
# Displays list of all topics.
def index(request):
    # Retreiving all the topics order_by published_date. '-published_date' for descending order. 
    listOfTopic = Topic.objects.order_by('-published_date')
    
    # loading the template
    # template = loader.get_template('xapp/index.html')
    
    # variable to be sent to view
    context = {
        'topics' : listOfTopic
    }
    
    # return HttpResponse(template.render(context, request))
    return render(request, 'xapp/index.html', context)
'''

# Displays list of all topics.
# Generic List View
class IndexView(generic.ListView):
    template_name = 'xapp/index.html'
    context_object_name = 'topics'

    def get_queryset(self):
        # Retreiving all the topics order_by published_date. '-published_date' for descending order.
        return Topic.objects.order_by('-published_date')

'''
# Displays all details related to specific topic.
def topic(request, topic_id):
    # Get details of topic with id = topic_id
    getDetailsOfTopic = get_object_or_404(Topic, id=topic_id)
    context = {
        'topic' : getDetailsOfTopic
    }
    return render(request, 'xapp/topic.html', context)
'''

# Displays all details related to specific topic.
# Generic Detail View
class TopicView(generic.DetailView):
    model = Topic
    template_name = 'xapp/topic.html'

'''
# Displays all details related to specific opinion
def opinion(request, opinion_id):
        # Get details of topic with id = topic_id
    getDetailsOfTOpininon = get_object_or_404(Opinion, id=opinion_id)
    context = {
        'opinion' : getDetailsOfTOpininon
    }
    return render(request, 'xapp/opinion.html', context)
'''

# Displays all details related to specific opinion
# Generic Detail View
class OpinionView(generic.DetailView):
    model = Opinion
    template_name = 'xapp/opinion.html'

# Vote action related to specific opinion
def vote(request, opinion_id):
    if request.method =='POST':
        # Get the Opinion with opinion_id from URL, if present else throw 404 Error
        opinion = get_object_or_404(Opinion, pk=opinion_id)

        # Check data type of variable using type()
        # print(type(request.POST['opinion-vote']))
        # print(type(opinion_id))

        # If opinion_id from URL matched the data obtained from request.POST then validate the vote  
        if (int(request.POST['opinion-vote']) == opinion_id):
            opinion.votes += 1
            opinion.save()

            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            return HttpResponseRedirect(reverse('xapp:opinion', args=(opinion_id, )))
        else:
            return HttpResponseRedirect(render(request, 'xapp/opinion.html', {
                'opinion': opinion,
                'error_message': "Error encountered while registering your vote",
            }))

    else:
        return HttpResponse('Method Not allowed !')

projectX/xapp/templates/xapp/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Home</title>
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'xapp/style.css' %}"
    />
  </head>

  <body>
    <div class="content">
      <table>
        {% if topics %} {% for topic in topics %}
        <tr>
          <td class="main-cell">
            <a href="{% url 'xapp:topic' topic.id %}">{{ topic.title }}</a>
          </td>
          <td>{{ topic.published_date }}</td>
        </tr>
        {% endfor %} {% else %}
        <p>No Topics are available.</p>
        {% endif %}
      </table>
    </div>
  </body>
</html>

projectX/xapp/templates/xapp/opinion.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Opinion</title>
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'xapp/style.css' %}"
    />
  </head>
  <body>
    <div class="content">
      <div class="header">
        <h1>Opinion - {{ opinion.id }}</h1>
        <h3>{{ opinion.opinion }}</h3>
      </div>
      <table>
        <tr>
          <td class="main-cell">Total no. of votes :</td>
          <td>{{ opinion.votes }} Votes</td>
        </tr>
        <tr>
          {% if error_message %}
          <p><strong>{{ error_message }}</strong></p>
          {% endif %}
          <form action="{% url 'xapp:vote' opinion.id %}" method="post">
            {% csrf_token %}
            <td class="main-cell">
              <label> Like the Opinion? Show support by voting</label>
            </td>
            <td>
              <input
                type="hidden"
                name="opinion-vote"
                value="{{ opinion.id }}"
              />
              <input
                class="button"
                type="submit"
                id="{{ opinion.id }}"
                value="Vote"
              />
            </td>
          </form>
        </tr>
      </table>
    </div>
  </body>
</html>

projectX/xapp/templates/xapp/topic.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{{ topic.title }}</title>
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'xapp/style.css' %}"
    />
  </head>
  <body>
    <div class="content">
      <div class="header">
        <h1>{{ topic.title }}</h1>
        <h3>Published at {{ topic.published_date }}</h3>
      </div>
      <table>
        {% for opinion in topic.opinion_set.all %}
        <tr>
          <td class="main-cell">
            <a href="{% url 'xapp:opinion' opinion.id %}"
              >{{ opinion.opinion }}</a
            >
          </td>
          <td>{{ opinion.votes }} Votes</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </body>
</html>